### ISSUE TITLE
예외 프로세스 선택 창에서 체크박스 선택 시 익셉션이 생기는 이슈

### ISSUE THREAD

**Issue by ryul99** [bumju08/EasyHCI#2]
예외 프로세스 선택 창에서 프로세스 이름이 아니라 프로세스 이름 왼쪽에 있는 체크박스를 선택 시 익셉션이 발생합니다.
https://github.com/bumju08/EasyHCI/blob/a9e94c1410787c2f94fb03e2e58712f086ab84b4/Forms/ProcessListForm.cs#L236-L242
여기에서 `selects`의 Count가 0으로 나오는데 추정하기로는 클릭으로 인식하는 영역과 선택으로 인식하는 영역이 다른 것 같습니다.

**Comment by Manbocoon** [comment]
안녕하세요, 해당 문제 수정했습니다.
프로그래밍 막 입문할 때 만든 것들 중 하나라서 프로젝트에 뜯어고칠 부분이 매우 많은데, 방치되고 있네요.
귀한 시간 들여 주셔서 감사합니다 :)

[ryul99님이 수정하신 부분에 해당 문제를 수정한 버전입니다.](https://github.com/bumju08/EasyHCI/releases/tag/1.0.8D)

**Comment by ryul99** [comment]
좋은 프로그램 만들어 주셔서 감사합니다ㅎㅎ 이 이슈는 닫겠습니다
